export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const REGISTER_USER = 'REGISTER_USER';
export const USER_REGISTERED = 'USER_REGISTERED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const REGISTER_FAILED = 'REGISTER_FAILED';