export const MY_TEAMS_FETCHED = 'MY_TEAMS_FETCHED';
export const TEAM_FETCHED = 'TEAM_FETCHED';
export const SELECTED_TEAM_RESET = 'SELECTED_TEAM_RESET';
export const LOAD_FIRST_TEAM = 'LOAD_FIRST_TEAM';
export const MEMBER_INPUT_SUGGESTIONS_FETCHED = 'MEMBER_INPUT_SUGGESTIONS_FETCHED';
export const CLEAR_MEMBER_SUGGESTIONS = 'CLEAR_MEMBER_SUGGESTIONS';